Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.memory = 1024
        libvirt.uri = 'qemu:///system'
    end

    config.vm.synced_folder ".", "/vagrant", type: "rsync",
            rsync__auto: true,
            rsync__exclude: [".git/"]

    config.vm.define "server" do |server|
        server.vm.box = "generic/ubuntu2004"
        server.vm.hostname = "server"
        server.vm.network :private_network, ip: "192.168.121.10"
        server.vm.provision "shell", path: "provisioning/server.sh"
    end

    config.vm.define "client" do |client|
        client.vm.box = "generic/ubuntu2004"
        client.vm.hostname = "client"
        client.vm.network :private_network, ip: "192.168.121.11"
        client.vm.provision "shell", path: "provisioning/client.sh", args: "192.168.121.10"
    end
end
