Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.memory = 1024
        libvirt.uri = 'qemu:///system'
        libvirt.default_prefix = 'vagrant_'
    end


    config.vm.define "server" do |server|
        server.vm.box = "generic/ubuntu2004"
        server.vm.hostname = "server"

        server.vm.network :private_network,
                type: "dhcp",
                libvirt__forward_mode: "nat"

        server.vm.provision "shell", path: "provisioning/server.sh"
        #server.vm.provision "shell", path: "provisioning/ssl/create_cert.sh"
        server.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define "client" do |client|
        client.vm.box = "generic/ubuntu2004"
        client.vm.hostname = "client"

        client.vm.network :private_network,
                type: "dhcp",
                libvirt__forward_mode: "nat"

        client.vm.provision "shell", path: "provisioning/client.sh"
        client.vm.synced_folder ".", "/vagrant", disabled: true
    end

end
